import {
    TextFields,
    Email,
    Notes,
    Numbers,
    CheckBox,
    List,
    RadioButtonChecked,
    CalendarMonth,
    Cake,
    Title,
    Article,
    AccountTree,
    Sell,
    Calculate,
    PlaylistAddCheck,
} from "@mui/icons-material";

export const FIELD_TYPE_ICONS: Record<string, React.ReactNode> = {
    TextFields: <TextFields />,
    Email: <Email />,
    Notes: <Notes />,
    Numbers: <Numbers />,
    CheckBox: <CheckBox />,
    List: <List />,
    RadioButtonChecked: <RadioButtonChecked />,
    CalendarMonth: <CalendarMonth />,
    Cake: <Cake />,
    Title: <Title />,
    Article: <Article />,
    AccountTree: <AccountTree />,
    Sell: <Sell />,
    Calculate: <Calculate />,
    PlaylistAddCheck: <PlaylistAddCheck />,
};
